[HUBDEV-2161] fixed the bug related when request sent wrong json body…
WSO2Telco/mediation-dep pull request #152
Opened 2018-10-25 10:58 UTC by MilindaLaknath

Fixed the bug related when request sent wrong json body to the operator hub. Proper error message returns.

2018-10-25 11:00 UTC, hasitha-sandanuwan commented
Can one of the admins verify this patch?

2018-10-25 11:05 UTC, MilindaLaknath commented
[HUBDEV-2159] fixed the bug related when request send without charging meta data type. Success message returns.

2018-10-26 04:01 UTC, jaadds requested changes

2018-10-26 04:01 UTC, jaadds commented on mediation-old/src/main/java/com/wso2telco/dep/mediator/impl/payment/AmountChargeHandler.java
>          log.debug("Hub / Gateway Id : " + hub_gateway_id);
As a practice, always wrap log.debug with log.isDebugEnabled() check. The reason is, debug logs are only enabled when needed additional information, but since we are passing arguments, those would get evaluated even when they are not needed.

2018-10-26 04:01 UTC, jaadds commented on mediation-old/src/main/java/com/wso2telco/dep/mediator/impl/payment/AmountChargeHandler.java
> +            boolean isaggrigator = paymentUtil.isAggregator(context);
Typo, should be isAggregator

2018-10-26 04:01 UTC, jaadds commented on mediation-old/src/main/java/com/wso2telco/dep/mediator/impl/payment/AmountChargeHandler.java
> +                if (!chargingdmeta.isNull("onBehalfOf")) {
Typo, should be chargingMeta

2018-10-26 04:01 UTC, jaadds commented on mediation-old/src/main/java/com/wso2telco/dep/mediator/impl/payment/AmountChargeHandler.java
> +                if (validCategoris == null || validCategoris.isEmpty() || (!validCategoris.contains(chargingdmeta.getString("purchaseCategoryCode")))) {
Typo, validCategories

2018-10-26 04:53 UTC, MilindaLaknath commented
Changes updated with following commit.
https://github.com/WSO2Telco/mediation-dep/pull/152/commits/6ead6c616eb044a7a1c337bd980cfed20b8d2f52

2018-10-26 05:31 UTC, MilindaLaknath commented
[HUBDEV-2161] Wrap debug log with log.isDebugEnabled() and Typo fixed.
https://github.com/WSO2Telco/mediation-dep/pull/152/commits/0b71e5d05426824fb90fad00867ea922e4792adc

2018-10-27 04:31 UTC, MilindaLaknath commented
[HUBDEV-2159] Changes updated. curly braces and indentation applied in if statements.

2018-10-27 06:32 UTC, jaadds approved these changes

2018-10-31 06:36 UTC, MilindaLaknath commented
Commit https://github.com/WSO2Telco/mediation-dep/pull/152/commits/5a15a7adc887fdc1b4bfb025c7f9c186e35047f8 changes related to [HUBDEV-2309]

2018-11-09 07:17 UTC, aushaniU approved these changes

2018-11-09 07:38 UTC, merged