HUBDEV-2314 : [Location API] : Error when changing the order of query param
WSO2Telco/mediation-dep pull request #153
Opened 2018-10-31 10:06 UTC by dsulochana

… param

2018-10-31 10:08 UTC, hasitha-sandanuwan commented
Can one of the admins verify this patch?

2018-11-06 04:28 UTC, aushaniU approved these changes

2018-11-06 04:37 UTC, aushaniU approved these changes

2018-11-06 05:49 UTC, jaadds requested changes

2018-11-06 05:49 UTC, jaadds commented on mediation-old/src/main/java/com/wso2telco/dep/mediator/impl/LocationExecutor.java
> +    ValidateLocation validator;
Declare this as a private variable.

2018-11-06 07:40 UTC, dsulochana commented on mediation-old/src/main/java/com/wso2telco/dep/mediator/impl/LocationExecutor.java
> +    ValidateLocation validator;
Modified..

2018-11-06 15:36 UTC, merged